import { NextRequest, NextResponse } from "next/server";
import { ai, MODEL } from "@/lib/genai";

function cleanJson(text: string) {
  return text.replace(/```json/g, "").replace(/```/g, "").trim();
}

function slugifyBranch(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s/-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 50);
}

function buildPrompt(input: {
  owner: string;
  repo: string;
  issue: {
    number: number;
    title: string;
    body?: string;
  };
  plan: {
    simpleExplanation?: string;
    steps?: string[];
    relevantFiles?: { path: string; why: string }[];
  };
  progress?: {
    status?: string;
    completedSessions?: number[];
    blocker?: string;
    baseBranchSuggestion?: string;
  };
}) {
  return `
You are generating a GitHub pull request draft for an open-source contribution.

Repository: ${input.owner}/${input.repo}
Issue #${input.issue.number}: ${input.issue.title}

Issue body:
${input.issue.body || "No issue body provided."}

Plan summary:
${input.plan.simpleExplanation || "No summary available."}

Steps:
${(input.plan.steps || []).map((s, i) => `${i + 1}. ${s}`).join("\n")}

Relevant files:
${(input.plan.relevantFiles || [])
  .map((f) => `- ${f.path}: ${f.why}`)
  .join("\n")}

Progress:
Status: ${input.progress?.status || "planned"}
Completed sessions: ${(input.progress?.completedSessions || []).join(", ") || "none"}
Blocker: ${input.progress?.blocker || "none"}
Suggested base branch: ${input.progress?.baseBranchSuggestion || "main"}

Return ONLY valid JSON:
{
  "branchName": "git-safe-branch-name",
  "baseBranch": "main",
  "title": "pull request title",
  "body": "markdown PR body",
  "checklist": ["item 1", "item 2", "item 3"]
}

Rules:
- branchName should be short and git-safe
- baseBranch should usually use the suggested base branch
- title should be concise
- body should mention the issue number
- checklist should be practical
`;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    if (!body?.owner || !body?.repo || !body?.issue || !body?.plan) {
      return NextResponse.json(
        { error: "Missing required fields for PR draft" },
        { status: 400 }
      );
    }

    const prompt = buildPrompt(body);

    const result = await ai.models.generateContent({
      model: MODEL,
      contents: prompt
    });

    const text = result.text || "";
    let parsed: any;

    try {
      parsed = JSON.parse(cleanJson(text));
    } catch {
      parsed = {};
    }

    const fallbackBranch = `feat/issue-${body.issue.number}-${slugifyBranch(
      body.issue.title || "update"
    )}`;

    return NextResponse.json({
      branchName: parsed.branchName || fallbackBranch,
      baseBranch:
        parsed.baseBranch ||
        body?.progress?.baseBranchSuggestion ||
        "main",
      title: parsed.title || `Resolve issue #${body.issue.number}`,
      body:
        parsed.body ||
        `## Summary\nAddresses #${body.issue.number}\n\n## Changes\n- Added planned contribution updates\n\n## Notes\n- Generated by Open Source Ally\n`,
      checklist: parsed.checklist || [
        "Review changed files",
        "Run relevant checks/tests",
        "Confirm issue requirements are addressed"
      ]
    });
  } catch (error: any) {
    console.error("PR DRAFT ERROR:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate PR draft" },
      { status: 500 }
    );
  }
}